// This file is autogenerated. Changes will be overwritten.
#include "UV6IQMH4VT/moc_guestregistration.cpp"
#include "UV6IQMH4VT/moc_registration.cpp"
#include "UV6IQMH4VT/moc_standardregistration.cpp"
#include "UV6IQMH4VT/moc_studentregistration.cpp"
