if(EXISTS "/home/runner/work/ConferenceRegistration/ConferenceRegistration/_codeql_build_dir/tests/unit/unit_tests[1]_tests.cmake")
  include("/home/runner/work/ConferenceRegistration/ConferenceRegistration/_codeql_build_dir/tests/unit/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
